const NOT_FOUND = 404;
const INTERNAL_SERVER_ERROR = 500;
const BAD_REQUEST = 400;
const OK = 200;
const CREATED = 201;
const CONFLICT = 409;
const UNAUTH_ERR = 401;
const FORBIDDEN = 403;

module.exports = {
  NOT_FOUND,
  INTERNAL_SERVER_ERROR,
  BAD_REQUEST,
  OK,
  CREATED,
  UNAUTH_ERR,
  FORBIDDEN,
  CONFLICT,
};
